# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 50090b25d76a550c20b7f95a350a8a74e182dbac33cd40f811b84ff62a9c527d3ec5acc57f1db823578f2d280dfff36dc255ab5d947775a38272bc4f1df8b9f7

test:
  secret_key_base: f1959c61d040824f32af0c4f9482dc25e8c3c0249dc17ba288a7183051b0ccfb528fc6d28ba5e48661c68e626756e354ca4bffe210dd99d45b912ef296c200c6

production:
  secret_key_base: 7b60d3adf6a6ba4d6ce399cd9d4234f88d5b4034d0b4df1775dda8f55d08ecd186c4f9d45dba94f4b929b69edfbb8820302f0d9988f6045b4a9edf16c915f99e
